
spring:
  application:
    name: ht-server
  datasource:
    first:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://${MYSQL_HOST:172.31.1.182}:${MYSQL_PORT:3307}/dbxc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: ${MYSQL_PASSWORD:123456}
    second:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://${MYSQL_HOST_2:172.31.1.111}:${MYSQL_PORT_2:3306}/dbxc?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: ${MYSQL_PASSWORD_2:123456}
  cloud:
    alibaba:
      seata:
        tx-service-group: ht-seata-group
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1}:${NACOS_PORT:8848}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

server:
  port: 9090

seata:
  enabled: true
  config:
    type: file

logging:
  level:
    io:
      seata: debug
